# nvfetcher.toml
[vast-release]
src.github_tag = "tenzir/vast"
src.include_regex = "v1.*"
fetch.github = "tenzir/vast"
git.fetchSubmodules = true


[vast-latest]
src.git = "https://github.com/tenzir/vast"
fetch.github = "tenzir/vast"
git.fetchSubmodules = true
