# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-latest = {
    pname = "vast-latest";
    version = "4af1b4d72a44fef9ed69834f885109e3cf3339dc";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "4af1b4d72a44fef9ed69834f885109e3cf3339dc";
      fetchSubmodules = true;
      sha256 = "sha256-JqRjXVbP9m1MfLbWE7VXQl1PSV01P8Hpis0TzFj4LLM=";
    });
  };
  vast-release = {
    pname = "vast-release";
    version = "v1.1.0-rc1";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "v1.1.0-rc1";
      fetchSubmodules = true;
      sha256 = "sha256-JqRjXVbP9m1MfLbWE7VXQl1PSV01P8Hpis0TzFj4LLM=";
    });
  };
}
