# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-latest = {
    pname = "vast-latest";
    version = "eb8c418693c3a593f246ae68712cc274576a527f";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "eb8c418693c3a593f246ae68712cc274576a527f";
      fetchSubmodules = true;
      sha256 = "sha256-EEXjtM9YfZANLybO9mnsKe8UMPpH5si56wEWHGsRPtg=";
    });
  };
  vast-release = {
    pname = "vast-release";
    version = "2021.10.35-rc3";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "2021.10.35-rc3";
      fetchSubmodules = true;
      sha256 = "sha256-u5JP5NSZLCWtBDNMfLtuaiMllF7ws1PTa31QvGQr6bg=";
    });
  };
}
