# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit
, fetchurl
, fetchFromGitHub
}:
{
  vast-latest = {
    pname = "vast-latest";
    version = "b4b7957b9d1093acff5c6f4b65c3646c5f8fc035";
    src = fetchFromGitHub (
      {
        owner = "tenzir";
        repo = "vast";
        rev = "b4b7957b9d1093acff5c6f4b65c3646c5f8fc035";
        fetchSubmodules = true;
        sha256 = "sha256-XT7tWeE6pizx5YWlOe4r71ZmV6j+ZOFhBgBuer8Quz4=";
      }
    );
  };
  vast-release = {
    pname = "vast-release";
    version = "v1.0.0";
    src = fetchFromGitHub (
      {
        owner = "tenzir";
        repo = "vast";
        rev = "v1.0.0";
        fetchSubmodules = true;
        sha256 = "sha256-7ZLudaPngR35rc6iBvuous+e5nb4cKKm19autLh4ick=";
      }
    );
  };
}
