[devshell]
packages = [ "navi" ]

[[commands]]
name = "vast-example"
category = "conf"
command = "vast --config=$PRJ_ROOT/conf/config.vast.example.yaml start"
help = "launch vast with example.yaml"

[[commands]]
name = "nvfetcher"
category = "Update"
command = "nix -Lv develop github:hardenedlinux/nixpkgs-hardenedlinux -c update nvfetcher ./nix/sources.toml"
help = "run nvfetcher for updating"
