# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-bin = {
    pname = "vast-bin";
    version = "v2.3.1";
    src = fetchurl {
      url = "https://github.com/tenzir/vast/releases/download/v2.3.1/vast-linux-static.tar.gz";
      sha256 = "sha256-8Esx4RAFDL7uZEG3xl6SaGNOS/E4Yu9Lhq5rijyyosc=";
    };
  };
  vast-latest = {
    pname = "vast-latest";
    version = "0eed355e81456a78b9ee48788f8595fd554d87b5";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "0eed355e81456a78b9ee48788f8595fd554d87b5";
      fetchSubmodules = true;
      sha256 = "sha256-VSeklPRfSDzm/zzcO2py/UDuBIni3qiOSjBz2AgEE0s=";
    });
    date = "2022-10-18";
  };
  vast-release = {
    pname = "vast-release";
    version = "v2.3.1";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "v2.3.1";
      fetchSubmodules = true;
      sha256 = "sha256-e82F1PR9mRgpAsrBENsr6/ljq9P0zRUaieQKoo/MRwo=";
    });
  };
}
