# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-bin = {
    pname = "vast-bin";
    version = "v2.3.0";
    src = fetchurl {
      url = "https://github.com/tenzir/vast/releases/download/v2.3.0/vast-linux-static.tar.gz";
      sha256 = "sha256-Rak6/qK6vwVUOtg4f/ErXghmUiQ00pGtASlsh692uoQ=";
    };
  };
  vast-latest = {
    pname = "vast-latest";
    version = "84889e9dc8640f86b005785fee35bd6ad916302c";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "84889e9dc8640f86b005785fee35bd6ad916302c";
      fetchSubmodules = true;
      sha256 = "sha256-YgmLSvq2XH/8/+nRPBZS07x+rzLLoe1BHHlIoRUCbJ8=";
    });
  };
  vast-release = {
    pname = "vast-release";
    version = "v2.3.0";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "v2.3.0";
      fetchSubmodules = true;
      sha256 = "sha256-dSZk6R6tgrPRq4qNTmq4e8ApCFG+CogNBNz0gRLuiGA=";
    });
  };
}
