# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/std/nixago/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# Show Vast documentation
doc help:
    nix run $PRJ_ROOT\#x86_64-linux.vast.entrypoints.doc {{ help }}

# Formats all changed source files
fmt:
    treefmt $(git diff --name-only --cached)
