#+title: Vast2nix

The *vast2nix* repo is still in work-in-process. You could discover some methods and inspiration in different examples as follows. Also, it would help you to understand how *nix/nixos* helps us to build a SOC platform and accomplish some automation jobs.

Getting started with [[https://incredible-haupia-862e63.netlify.app/][Online Document]]

* [[https://github.com/input-output-hk/cardano-world/blob/master/docs/explain/packaging-principles.md][The 4 Layers of Packaging]]

Vast2nix is based on [[https://github.com/divnix/std/blob/main/docs/patterns/four-packaging-layers.md][The 4 Layers of Packaging]] of std.

- The OCI image packaging: [[file:nix/vast/oci-images/default.nix]]
  + The entrypoint packaging [[file:nix/vast/operables/default.nix]]

- The entrypoint packaging [[file:nix/vast/entrypoints/default.nix]]
- The binary packaging [[file:nix/vast/packages/default.nix]]

* Generator

How is *vast2nix* genarated `configFiles/config`


- [[file:nix/vast/config]]
- [[file:nix/vast/configFiles]]

* Operations

How is *vast2nix* operated *task/platform/cloud/workflow/vast-intergation*

- [[file:nix/query/entrypoints/default.nix::9]]

* Render

How is *vast2nix* rendered *vast-schemas/attack-models/dataTypes/*

- converting Phishing-url *jsonSchema* -> vast-schemas
  - [[file:nix/schemas/config/default.nix::9]]

* Devshell

How is *vast2nix* hooked virtual shell with different environment profiles. -> *zeek(btest,zeekScript,zeek-language-server)/vast(vast-intergation,pyvast)/theHive/zed/etc/*

** [[https://github.com/numtide/devshell][devshell]] Intergation

- [[file:nix/vast/devshells/default.nix]]
  + [[file:nix/vast/devshellProfiles/default.nix]]

** devContainer OCI-image Intergation

#+begin_src sh
docker pull ghcr.io/gtrunsec/quarto-dev:latest
docker run -it -v "$(pwd):/work" --entrypoint /bin/bash ghcr.io/gtrunsec/quarto-dev
menu
#+end_src


* Real SOC Planet with Nix/Declarative EcoSystem

- https://github.com/GTrunSec/hunting-lab
