# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-bin = {
    pname = "vast-bin";
    version = "v2.0.0";
    src = fetchurl {
      url = "https://github.com/tenzir/vast/releases/download/v2.0.0/vast-linux-static.tar.gz";
      sha256 = "sha256-KhnDQC6H+CiVDj8ORUV1aLAVP+Cww5fLw/W2IrQv4Zk=";
    };
  };
  vast-latest = {
    pname = "vast-latest";
    version = "375ab3648c5ba0763b683d88c4d8cf0ee98d4f3e";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "375ab3648c5ba0763b683d88c4d8cf0ee98d4f3e";
      fetchSubmodules = true;
      sha256 = "sha256-QyP7XX2EPHpRB3x9VDNMh/F2k7JiM/TEU/5Uj8KJRyE=";
    });
  };
  vast-release = {
    pname = "vast-release";
    version = "v2.1.0-rc2";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "v2.1.0-rc2";
      fetchSubmodules = true;
      sha256 = "sha256-wbMNQSPSBx6Pqx88XcubC3/eq955uKxlyENsyXZ+cTs=";
    });
  };
}
