# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vast-bin = {
    pname = "vast-bin";
    version = "v2.1.0";
    src = fetchurl {
      url = "https://github.com/tenzir/vast/releases/download/v2.1.0-rc3/vast-linux-static.tar.gz";
      sha256 = "sha256-wY37OMDwvecirzAHxdUG3H31mPNZy25niUTlaU21UTw=";
    };
  };
  vast-latest = {
    pname = "vast-latest";
    version = "9ac8ab1cdc29d4bb589b124fe70273546bf46bf3";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "9ac8ab1cdc29d4bb589b124fe70273546bf46bf3";
      fetchSubmodules = true;
      sha256 = "sha256-3W2735Q5pxz3PuEHX3axU9P0nf+MFQLTFTgyvZ8/jN8=";
    });
  };
  vast-release = {
    pname = "vast-release";
    version = "v2.2.0-rc1";
    src = fetchFromGitHub ({
      owner = "tenzir";
      repo = "vast";
      rev = "v2.2.0-rc1";
      fetchSubmodules = true;
      sha256 = "sha256-3W2735Q5pxz3PuEHX3axU9P0nf+MFQLTFTgyvZ8/jN8=";
    });
  };
}
