# nvfetcher.toml
[vast-release]
src.github_tag = "tenzir/vast"
src.include_regex = "v2.*"
fetch.github = "tenzir/vast"
git.fetchSubmodules = true

[vast-latest]
src.git = "https://github.com/tenzir/vast"
fetch.github = "tenzir/vast"
git.fetchSubmodules = true

[vast-bin]
src.github = "tenzir/vast"
fetch.url = "https://github.com/tenzir/vast/releases/download/v2.1.0-rc3/vast-linux-static.tar.gz"
