name: "CI"
on:
  push:
    branches: [main, staging, trying]
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220611_37fc4d7/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v11
        with:
          name: zeek
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Flake Show
        run: nix -Lv flake show

      - name: Run Updates
        run: nix -Lv develop -c nvfetcher-update

      - name: Build Release vast
        run: nix -Lv build .#vast-release
      - name: Check Release vast Exec
        run: nix run ./#vast-release -- --help

      - name: Build Latest vast
        run: nix -Lv build .#vast-latest
      - name: Check Latest vast Exec
        run: nix run ./#vast-latest -- --help
      - name: Check Latest vast Plugins
        run: nix run ./#vast-latest -- import -h

      - name: Build Release pyvast
        run: nix -Lv build .#pyvast

      - name: Build Latest pyvast
        run: nix -Lv build .#pyvast-latest

        # limited host resoure on github CI
        # - name: Check Vast with Systemd on NixOS-VM
        #   run: nix -Lv build .#vast-vm-systemd

      - name: Commit changes
        if: ${{ env.COMMIT_MSG != null }}
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MSG }}

      - name: Build Doc
        run: nix -Lv develop --command mdbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: ./docs/book
